FIXTURES_TEST_SCRAPE = [
    ['Ireland'],
['15', 'Hugo', 'Keenan'],
['14', 'Andrew', 'Conway'],
['13', 'Garry', 'Ringrose'],
['12', 'Bundee', 'Aki'],
['11', 'Mack', 'Hansen'],
['10', 'Johnny', 'Sexton'],
['9', 'Jamison', 'Gibson-Park'],
['1', 'Andrew', 'Porter'],
['2', 'Ronan', 'Kelleher'],
['3', 'Tadhg', 'Furlong'],
['4', 'Tadhg', 'Beirne'],
['5', 'James', 'Ryan'],
['6', 'Caelan', 'Doris'],
['7', 'Josh', 'van', 'der', 'Flier'],
['8', 'Jack', 'Conan'],
['16', 'Dan', 'Sheehan'],
['17', 'Cian', 'Healy'],
['18', 'Finlay', 'Bealham'],
['19', 'Ryan', 'Baird'],
['20', 'Peter', "O'Mahony"],
['21', 'Conor', 'Murray'],
['22', 'Joey', 'Carbery'],
['23', 'James', 'Hume'],
['Wales'],
['15', 'Liam', 'Williams'],
['14', 'Johnny', 'McNicholl'],
['13', 'Josh', 'Adams'],
['12', 'Nick', 'Tompkins'],
['11', 'Louis', 'Rees-Zammit'],
['10', 'Dan', 'Biggar'],
['9', 'Tomos', 'Williams'],
['1', 'Wyn', 'Jones'],
['2', 'Ryan', 'Elias'],
['3', 'Tomas', 'Francis'],
['4', 'Will', 'Rowlands'],
['5', 'Adam', 'Beard'],
['6', 'Ellis', 'Jenkins'],
['7', 'Taine', 'Basham'],
['8', 'Aaron', 'Wainwright'],
['16', 'Dewi', 'Lake'],
['17', 'Gareth', 'Thomas'],
['18', 'Dillon', 'Lewis'],
['19', 'Ben', 'Carter'],
['20', 'Ross', 'Moriarty'],
['21', 'Gareth', 'Davies'],
['22', 'Callum', 'Sheedy'],
['23', 'Owen', 'Watkin'],
['{{', 'event.player.lastName', '}}', '({{', 'event.rounded_minutes', "}}')", '{{', 'playerMultipleScores(event,', 'index,', 'eventObj.events)', '}}', '({{', 'event.rounded_minutes', "}}')"],
['{{', 'event.player.lastName', '}}', '({{', 'event.rounded_minutes', "}}')"],
['{{', 'playerStats.teams.teamA.name', '}}', '{{', 'playerStats.teams.teamB.name', '}}'],
['Replacements'],
]